### PR TITLE
Update invest optimization example according to v0.2.2

### PR DESCRIPTION
**Pull request by FabianTU**

### CODE REVIEW

**Comment by uvchik** [comment]
Thank you for the example, you only have to change the required version from `v0.2.0` to `v0.2.2`.

If you want you could explain the results a little bit but you do not have to.

What I do not understand is the way you define the investment costs:
```python
storage1 = solph.components.GenericStorage(
    label='storage1',
    inputs={bel: solph.Flow(investment = solph.Investment(ep_costs=epc_storage, maximum=100000))},
    outputs={bel: solph.Flow(investment = solph.Investment(ep_costs=0))},
    capacity_loss=0.00, initial_capacity=0,
    invest_relation_input_capacity=1/6,
    invest_relation_output_capacity=1/6,
    inflow_conversion_factor=1, outflow_conversion_factor=0.8,
    investment=solph.Investment(ep_costs=epc_storage),
)
```

The input has cost, the output is for free and the capacity has costs. If all variables are couple I would define all parameters in one Investment object and leave the other empty to avoid confusions.

In you case the costs for one unit storage capacity are: `epc_storage + 1/6 * epc_storage` and the maximum capacity is 600000 [`100000 / (1/6)`]. Therefore I would calculate overall periodical costs `epc_storage_all` and define the storage like this:

```python
storage1 = solph.components.GenericStorage(
    label='storage1',
    inputs={bel: solph.Flow(investment = solph.Investment())},
    outputs={bel: solph.Flow(investment = solph.Investment())},
    capacity_loss=0.00, initial_capacity=0,
    invest_relation_input_capacity=1/6,
    invest_relation_output_capacity=1/6,
    inflow_conversion_factor=1, outflow_conversion_factor=0.8,
    investment=solph.Investment(ep_costs=epc_storage_all, maximum=600000),
)
```

if you want to build up an PHES you could model all components independently:

```python
storage1 = solph.components.GenericStorage(
    label='storage1',
    inputs={bel: solph.Flow(investment = solph.Investment(
        ep_costs=epc_pump, maximum=pump_max))},
    outputs={bel: solph.Flow(investment = solph.Investment(
        ep_costs=epc_turbine, maximum=turbine_max))},
    capacity_loss=0.00, initial_capacity=0,
    inflow_conversion_factor=1, outflow_conversion_factor=0.8,
    investment=solph.Investment(ep_costs=epc_basin, maximum=basin_max),
)
```

**Comment by FabianTU** [comment]
@uvchik  My reasoning not to include your proposals is to show different possibilities to use the storage including the flows. Of Course those examples probably won't picture a real storage.

**Comment by uvchik** [comment]
I like more concrete in an example, so I would speak of batteries and phes and so on. Furthermore, for me it makes no sense to couple the investment variables (tie it to one component) and then define different cost for the units. At least this is a very special case. But it is your example.

Please change the required version from `v0.2.0` to `v0.2.2`.

If you are done we can merge.

**Comment by FabianTU** [comment]
As I learned there are no such things as stupid questions..  how do I Change the required Version?

**Comment by uvchik** [comment]
It's just text in the header:

https://github.com/oemof/oemof_examples/pull/23/files#diff-eae99bbdb686eb20aa44a9ac4b608ac6R47

Thank you.

**Pull request merged**
